#!/usr/bin/awk -f

BEGIN {
  ZARGV[1]=ARGV[1]
  ARGV[1]=""
}

/^[^💝]/ || // {
  print $0
}

/^## / {
  ZORS=ORS; ORS=""
  $1 = ""
  gsub(/ \(.*\)/, "")
  project = $0
  print "💝[Interested in sponsoring?](mailto:cross-info@ucsc.edu?"
  print "subject="ZARGV[1]": Sponsoring "project
  print "&body=Dear "ZARGV[1]" Staff, "
  print "I am interested in sponsoring summer student internships at $9,500 per student"
  ORS=ZORS
  print " for the project"project".)"
  print ""
}

/^### / {
  ZORS=ORS; ORS=""
  print "💝[Interested in sponsoring?](mailto:cross-info@ucsc.edu?"
  print "subject="ZARGV[1]": Sponsoring "project
  print "&body=Dear "ZARGV[1]" Staff, "
  print "I am interested in sponsoring summer student internships at $9,500 per student"
  ORS=ZORS
  print " for the project"project".)"
  print ""
}
